<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Apply | SL Academy</title><link rel="icon" type="image/png" href="{{ asset('images/logo-01.png') }}">@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body>
@include('partials.public-nav')
<main><section class="section" style="padding-bottom:35px"><div class="container"><span class="eyebrow">Start here / Enrollment</span><h1 class="display">Choose your<br><em>learning path.</em></h1><p class="lede">Select a grade and subject from the SL Academy school programme.</p></div></section>
<div class="form-shell"><form action="#" method="POST"><div class="form-grid"><div class="form-field"><label for="fullname">Full name *</label><input class="form-control" id="fullname" name="fullname" required></div><div class="form-field"><label for="email">Email address *</label><input class="form-control" type="email" id="email" name="email" required></div><div class="form-field"><label for="phone">Phone number</label><input class="form-control" type="tel" id="phone" name="phone"></div><div class="form-field"><label for="grade">Grade *</label><select class="form-control" id="grade" name="grade" required><option value="">Choose a grade</option>@for ($grade = 1; $grade <= 11; $grade++)<option value="{{ $grade }}">Grade {{ $grade }}</option>@endfor</select></div><div class="form-field form-field--wide"><label for="subject">Subject *</label><select class="form-control" id="subject" name="subject" required><option value="">Choose a subject</option><option>Sinhala</option><option>Tamil</option><option>English</option><option>Environmental Studies</option><option>Mathematics</option><option>Science</option><option>History</option><option>Geography</option><option>Civic Education</option><option>Religion</option><option>ICT</option><option>Health & Physical Education</option><option>Aesthetic Studies</option><option>Business & Accounting</option></select></div><div class="form-field form-field--wide"><label for="message">Anything we should know?</label><textarea class="form-control" id="message" name="message" rows="5"></textarea></div></div><button class="button button--dark button--large" type="submit">Send my application <span>↗</span></button></form></div></main>
@include('partials.public-footer')
</body>
</html>
