<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>SL Academy | Learn loudly</title><link rel="icon" type="image/png" href="{{ asset('images/logo-01.png') }}">@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body>
@include('partials.public-nav')
<main>
<section class="hero"><div class="container"><div class="hero-school reveal"><img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1800&q=90" alt="Students learning in a bright school classroom"><div class="hero-school__shade"></div><div class="hero-school__copy"><span class="eyebrow">SL Academy / Learning starts here</span><h1>Welcome to SL academy</h1><p>Transforming Education Through Innovation</p><a class="button button--lime button--large" href="{{ url('courses') }}">Explore Grades 1—11 <span>↗</span></a></div></div></div></section>
<div class="ticker"><div class="ticker__track"><span>learn by doing</span><span>grow with confidence</span><span>every grade matters</span><span>learn by doing</span><span>grow with confidence</span><span>every grade matters</span></div></div>
<section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">The school / 02</span><h2>One journey.<br>Every <em>grade.</em></h2></div><p>From Primary Grade 1 to Grade 11, students build strong foundations across languages, mathematics, science, culture, and technology.</p></div><div class="card-grid"><a class="course-card" href="{{ url('courses') }}"><div class="course-card__body"><span class="course-card__tag">Primary school / 01—05</span><h3>Start with confidence</h3><p>Sinhala, Tamil, English, Environmental Studies, and Mathematics for curious young minds.</p><div class="course-card__foot"><span>Grades 1—5</span><strong>↗</strong></div></div></a><a class="course-card" href="{{ url('courses') }}"><div class="course-card__body"><span class="course-card__tag">Secondary school / 06—11</span><h3>Build your direction</h3><p>Languages, Mathematics, Science, History, ICT, and the subjects that open future paths.</p><div class="course-card__foot"><span>Grades 6—11</span><strong>↗</strong></div></div></a><a class="course-card" href="{{ url('courses') }}"><div class="course-card__body"><span class="course-card__tag">Subject studio / All</span><h3>Find your subject</h3><p>Filter every grade and explore the full SL Academy subject programme.</p><div class="course-card__foot"><span>All subjects</span><strong>↗</strong></div></div></a></div></div></section>
<section class="band section"><div class="container feature-row"><img class="feature-image" src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1100&q=85" alt="Students learning together"><div><span class="eyebrow">Why SL / 03</span><div class="section-heading"><h2>Learning that feels <em>alive.</em></h2></div><ul class="feature-list"><li><b>01</b><span>A complete school programme from Grade 1 through Grade 11.</span></li><li><b>02</b><span>Clear teaching and practice across every core subject.</span></li><li><b>03</b><span>A caring environment where every student can grow.</span></li></ul></div></div></section>
<section class="section"><div class="container"><div class="stats"><div class="stat"><strong>1—11</strong><span>complete grade journey</span></div><div class="stat"><strong>16+</strong><span>subject pathways</span></div><div class="stat"><strong>5</strong><span>primary subjects</span></div><div class="stat"><strong>1</strong><span>shared school community</span></div></div></div></section>
</main>
@include('partials.public-footer')
</body></html>
